### ISSUE TITLE
TypeError: needs a 'context' argument when running tests

### ISSUE THREAD

**Issue by juanpaco** [thatdutchguy/windtunnel#1]
I have a series of tests in a jspec folder, and when I go to run them using `wt jspec`, I get the above error.  Here is a full dump of what it gives me:

TypeError: needs a 'context' argument.
    at Object.sandbox.getGlobal (/usr/local/lib/node_modules/windtunnel/node_modules/jsdom/lib/jsdom/browser/index.js:26:21)
    at Object.exports.createWindow (/usr/local/lib/node_modules/windtunnel/node_modules/jsdom/lib/jsdom/browser/index.js:308:23)
    at Object.exports.windowAugmentation (/usr/local/lib/node_modules/windtunnel/node_modules/jsdom/lib/jsdom/browser/index.js:63:24)
    at Object.parentWindow (/usr/local/lib/node_modules/windtunnel/node_modules/jsdom/lib/jsdom/browser/index.js:605:28)
    at Object.exports.jsdom.doc.createWindow (/usr/local/lib/node_modules/windtunnel/node_modules/jsdom/lib/jsdom.js:81:15)
    at createContext (/usr/local/lib/node_modules/windtunnel/lib/windtunnel/index.js:42:25)
    at Object.module.exports.runFile (/usr/local/lib/node_modules/windtunnel/lib/windtunnel/index.js:115:19)
    at Object.module.exports.runPath (/usr/local/lib/node_modules/windtunnel/lib/windtunnel/index.js:134:12)
    at Object.module.exports.run (/usr/local/lib/node_modules/windtunnel/lib/windtunnel/index.js:91:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/windtunnel/bin/wt:32:4)

**Comment by juanpaco** [comment]
I updated node from 0.6.0 to 0.9.0 and reinstalled the contextify package.  The tests run again.

**Comment by thatdutchguy** [comment]
Seems to be an issue with a jsdom dependency. I've tested on node 0.6.x and 0.8.x, and it should work.
